### ISSUE TITLE
Odd eckit mpi problem sporadic on containers

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA/eckit#7]
In all of the new container images, I sporadically get problems with eckit and MPI. I haven't looked into it very closely, but want to flag it and see your thoughts.

eckit is built with MPI, and /usr/local/include/eckit/eckit_config.h defines ECKIT_HAVE_MPI. oops doesn't detect this.

```
-- [oops] (0.2.1) [0949001]
-- Found package MKL required for feature MKL
-- Feature MKL enabled
-- Found package OMP required for feature OMP
-- Feature OMP enabled
-- [eckit] (1.4.0)
CMake Error at ecbuild/cmake/ecbuild_log.cmake:163 (message):
  ERROR - OOPS requested to build with MPI but eckit wasn't built with
  MPI: ECKIT_HAVE_MPI = 
Call Stack (most recent call first):
  oops/CMakeLists.txt:92 (ecbuild_error)
```

**Comment by mmiesch** [comment]
@rhoneyager - you might try downloading the containers again.  With the odc additions, I have been generating and re-generating a lot this week and there was one build in there where I think I was using the wrong branch of jedi-stack, which was installing the release-stable branch of ecbuild.  This ecbuild branch is old - based on upstream 2.9.4.   I have seen that MPI error with the old ecbuild versions and it is solved with upstream v 3.1.0, and our newer branches such as jcsda-feature-test_lists which are based on it.

All containers are built with a ```/etc/jedi-stack-contents.log```.  This should list ```ecbuild jcsda-feature-test_lists``` as the intended current working branch.  If that is not the case, try pulling the container again.  If it is still messed up let me know.

**Comment by rhoneyager** [comment]
Just pulled the Intel 17 container from S3. It is still using the jcsda-bugfix-old-linker branch.

**Comment by mmiesch** [comment]
oh yeah - that one is the exception because of the old linker.  The old linker branch does have test_lists merged in so that is correct.  Are you still seeing the ECKIT_HAVE_MPI problem with that?

**Comment by rhoneyager** [comment]
Yes

**Comment by mmiesch** [comment]
Hmm.. ok - I'll look into it.

**Comment by rhoneyager** [comment]
I will just use an older version of that container as a workaround... and will likely drop Intel 17 entirely once the Intel 19 container becomes the default for CI testing.

**Comment by mmiesch** [comment]
Yes - I agree - as soon as they fix the bug with the component install, we'll use intel 19 for CI and I'll probably stop maintaining the intel17.

**Comment by mmiesch** [comment]
@rhoneyager - did you say this was sporadic?  I just built ufo-bundle in the intel17 charliecloud container and had no problems - it compiled fine and all tests passed:
~~~~~
100% tests passed, 0 tests failed out of 442
~~~~~
I uploaded this again to S3 to make sure that version is the same one I ran but the size is the same as before so I think the one on S3 was up to date even before my push.  If you see it again please let me know more of the circumstances if you can.

**Comment by mmiesch** [comment]
Also - remember that eckit is installed in /usr/local so it should not be compiled with the bundle.
